# Generated by Django 4.2.9 on 2024-01-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
