# Generated by Django 4.2.9 on 2024-12-01 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_is_notified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
