# Generated by Django 4.2.9 on 2024-12-01 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='message_send',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_notified',
            new_name='task_done',
        ),
    ]
