# Generated by Django 4.2.9 on 2024-12-01 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_is_completed_task_message_send_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
