# Generated by Django 4.2.9 on 2024-12-02 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_created_at_task_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
